#!/bin/sh -e

usage() {
cat<<'EOF'
Makes `kpatch'es for the makesystem in the current directory.

Usage:	libcare-patch-make [-h|--help] [-u|--update || -c|--clean]
	[-s|--srcdir=SRCDIR] \
	[-d|--destdir=DESTDIRVAR] \
	[-j|--jobs=<number of jobs>] \
	PATCH1 PATCH2 ...

Run from inside the directory with `make'ble software. Makesystem must support
install with specified DESTDIR.

  -c --clean	do a clean build, execute `make clean` first
  -u --update	only update existing patches without rebuild. useful when
		working on patch utils.
  -s --srcdir	
  -d --destdir	specify variable makefile system uses to specify destination
		directory for the installation
  -j --jobs		specify variable makefile system jobs of compile, like `make -j 4`
		is startup `4` jobs to compile.
EOF
		exit ${1-0}
}

# 
# warn - print warn log
# info - print info log
function debug_log()
{
	case $1 in
	warn) 
		echo -e "\033[1;31m[WARN]\033[m $2"
		;;
	info) 
		echo -e "\033[1;32m[WARN]\033[m $2"
		;;
	debug) 
		echo -e "\033[1;33m[DEBG]\033[m $2"
		;;
	*)
		echo -e "\033[1;34m[DEBG]\033[m $1"
		;;
	esac
	read -r -p "Press any key to continue..." __input
}

prepare_env() {
	KPATCH_PATH=$(dirname $0)

	if test ! -x "$KPATCH_PATH/kpatch_gensrc"; then
		echo "kpatch tools are missing" >&2
		exit 1
	fi

	debug_log "Change CC to $KPATCH_PATH/libcare-cc"
	# redirect cc to libcare-cc
	export IS_LIBCARE_CC=y
	export CC=$KPATCH_PATH/libcare-cc
	export CXX=$CC

	MAKE_OUTPUT=/dev/stdout

	LPMAKEFILE=""
	test -f lpmakefile && LPMAKEFILE="-f lpmakefile"

	LPMAKE_ORIGINAL_DIR="${LPMAKE_ORIGINAL_DIR-$PWD/lpmake}"
	LPMAKE_PATCHED_DIR="${LPMAKE_PATCHED_DIR-$PWD/.lpmaketmp/patched}"
	LPMAKE_PATCHROOT="${LPMAKE_PATCHROOT-$PWD/patchroot}"

	export LPMAKE_ORIGINAL_DIR LPMAKE_PATCHED_DIR LPMAKE_PATCHROOT
	mkdir -p "$LPMAKE_ORIGINAL_DIR" "$LPMAKE_PATCHED_DIR" "$LPMAKE_PATCHROOT"

	unset MAKELEVEL
	unset MAKEFLAGS

	red=$(tput setaf 1)
	green=$(tput setaf 2)
	reset=$(tput sgr0)
}

restore_origs() {
	find $srcdir -regex '.+\.[0-9]+\.lpmakeorig' | awk '
	{
		origfname = $0;
		gsub("\.[0-9]+\.lpmakeorig$", "");
		fname = $0;
		if (!vers[fname] || vers[fname] > origfname)
			{ vers[fname] = origfname; }
	}
	END { for (f in vers) system("mv " vers[f] " " f); }
'
}

# src + patch = patch.src
# and trap singal like SIGINT
trap "restore_origs" 0

build_objects() {
	restore_origs
	
	JOBS_MAKE=""
	test $jobs_make && JOBS_MAKE="-j $jobs_make"

	# --clean 
	if test -n "$do_clean"; then
		debug_log "make $LPMAKEFILE clean"
		make $LPMAKEFILE clean >$MAKE_OUTPUT 2>&1
		rm -rf "$LPMAKE_ORIGINAL_DIR" "$LPMAKE_PATCHED_DIR"
	fi

	export KPATCH_STAGE=original
	export KPCC_DBGFILTER_ARGS=""

	# compile -> make
	echo "${green}BUILDING ORIGINAL CODE${reset}"
	debug_log "compile original code: make $LPMAKEFILE $JOBS_MAKE"
	make $LPMAKEFILE $JOBS_MAKE >$MAKE_OUTPUT 2>&1
	
	# install oroginal  
	# lpmake
	echo "${green}INSTALLING ORIGINAL OBJECTS INTO $LPMAKE_ORIGINAL_DIR${reset}"
	debug_log "install original elf: CC=$CC, make $LPMAKEFILE install $destdir=$LPMAKE_ORIGINAL_DIR"
	make $LPMAKEFILE install				\
		"$destdir=$LPMAKE_ORIGINAL_DIR"			\
		>$MAKE_OUTPUT 2>&1

	local oldpwd="$(pwd)"
	# string length is not 0
	if test -n "$srcdir"; then
		cd "$srcdir"
	fi

	i=0
	for patch; do
		# applying ../qemu-6.1.0.patch/0002-qemu-img.patch...
		echo "${red}applying $patch...${reset}"
		# -b  make backup file
		# -z
		# -p  
		#  src.c + src.patch = src-patch.c 
		debug_log "recover patch code: PWD=$PWD, ==> $patch ==> .${i}.lpmakeorig"
		patch -b -z .${i}.lpmakeorig -p1 < $patch
	done
	
	#echo "============================================================="
	if test -n "$srcdir"; then
		cd "$oldpwd"
	fi

	export KPATCH_STAGE=patched
	export KPCC_APPEND_ARGS="-Wl,-q"

	# compile patch.c
	echo "${green}BUILDING PATCHED CODE${reset}"
	debug_log "compile patch code: CC=$CC, make $LPMAKEFILE $JOBS_MAKE"
	make $LPMAKEFILE $JOBS_MAKE >$MAKE_OUTPUT 2>&1
	debug_log "Now, generate src.s and patch.s"

	# 
	# .lpmaketmp/patched
	echo "${green}INSTALLING PATCHED OBJECTS INTO $LPMAKE_PATCHED_DIR${reset}"
	debug_log "install patched code: CC=$CC, make $LPMAKEFILE install $destdir=$LPMAKE_PATCHED_DIR"
	make $LPMAKEFILE install				\
		"$destdir=$LPMAKE_PATCHED_DIR"			\
		>$MAKE_OUTPUT 2>&1
}

build_kpatches() {
	# make patchroot dir
	mkdir -p "${LPMAKE_PATCHROOT}"
	
	echo "${green}MAKING PATCHES${reset}"
	debug_log "Start to make patches"

	# loop all chmod exec file under lpmake 
	for execfile in $(find "$LPMAKE_ORIGINAL_DIR" -perm /0111 -type f); do
		# ELF  file with whole path
		origexec="$execfile"
		# ELF  file no path
		filename="${origexec##*$LPMAKE_ORIGINAL_DIR/}"
		#  .lpmaketmp/patched/foo
		# this ELF has .kpatch section 
		patchedexec="$LPMAKE_PATCHED_DIR/$filename"
	
		#echo "origexec = $origexec"
		#echo "filename = $filename"
		#echo "patchedexec = $patchedexec"

		# find ELF Build ID
		# NOTE: original ELF's Build ID is different with kpatch ELF
		buildid=$(eu-readelf -n "$origexec" | sed -n '/Build ID:/ { s/.* //; p }')

		debug_log "Get $origexec's Build ID = $buildid"
		#echo "$origexec Build ID = $buildid"
		# ELF must contain .kpatch* section
		# -q: quiet
		if ! eu-readelf -S "$patchedexec" | grep -q '.kpatch'; then
			debug_log "$patchedexec Not contain .kpatch section"
			continue
		fi

		test -n "$buildid" || continue

		debug_log "$patchedexec contain .kpatch section"

		# chmod execute
		chmod u+w "${origexec}" "${patchedexec}"

		debug_log "Strip the sections that is not .kpatch in ${patchedexec}"
		# Striping section
		$KPATCH_PATH/kpatch_strip --strip "${patchedexec}" \
			"${patchedexec}.stripped" >/dev/null
		$KPATCH_PATH/kpatch_strip --rel-fixup "$origexec" \
			"${patchedexec}.stripped" || continue
		/usr/bin/strip --strip-unneeded "${patchedexec}.stripped"
		$KPATCH_PATH/kpatch_strip --undo-link "$origexec" "${patchedexec}.stripped"
		# Generate kpatch hot patch
		debug_log "Generate HOT patch: ${LPMAKE_PATCHROOT}/${buildid}.kpatch"
		$KPATCH_PATH/kpatch_make -b "$buildid" \
			"${patchedexec}.stripped" -o "${patchedexec}.kpatch"
		cp "${patchedexec}.kpatch" "${LPMAKE_PATCHROOT}"/${buildid}.kpatch
		debug_log "warn" "patch for ${origexec} is in ${LPMAKE_PATCHROOT}/${buildid}.kpatch"
	done
}

main() {
	PROG_NAME=$(basename $0)

	TEMP=$(getopt -o s:ucdj: --long srcdir:,update,clean,destdir: -n ${PROG_NAME} -- "$@" || usage 1)
	eval set -- "$TEMP"

	destdir="DESTDIR"
	while true; do
		case $1 in
		-s|--srcdir)
			shift
			srcdir="$1"
			shift
			;;
		-u|--update)
			shift
			only_update=1
			;;
		-c|--clean)
			shift
			do_clean=1
			;;
		-d|--destdir)
			shift
			destdir=$1
			shift
			;;
		-j|--jobs)
			shift 
			jobs_make=$1
			shift
			;;
		--)
			shift; break;
			;;
		esac
	done

	prepare_env
	
	# String length is zero
	if test -z "$only_update"; then
		build_objects "$@"
	fi
	build_kpatches
}

debug_log "Ready to start"
main "$@"
